spring:
  application.name: spring-cache-redis

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    redis:
      enable-statistics: true
      time-to-live: PT60S


management:
  endpoints.web.exposure.include: '*'