apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cache-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cache-redis
  template:
    metadata:
      labels:
        app: spring-cache-redis
    spec:
      containers:
        - name: app
          image: spring-cache-redis:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
---
apiVersion: v1
kind: Service
metadata:
  name: spring-cache-redis
spec:
  selector:
    app: spring-cache-redis
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080