services:
  app:
    image: 'docker.io/library/postgresql-r2dbc:0.0.1-SNAPSHOT'
    depends_on:
      db:
        condition: service_healthy
     # Not recognised configuration
    environment:
      - 'SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/postgres'
      - 'SPRING_R2DBC_USERNAME=postgres'
      - 'SPRING_R2DBC_PASSWORD=secret'
    ports:
      - '8080:8080'
  db:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 2s
      retries: 3
