spring.application.name: micrometer-otlp


management:
  # disable all registries
  defaults:
    metrics:
      export:
        enabled: false

  # publishing metrics for DynatraceMeterRegistry every 5s
  dynatrace:
    metrics:
      export:
        step: "5s"

#  tracing:
#    enabled: false

