version: "3"
services:
  db:
    container_name: db
    image: 'postgres:16'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
  vault:
    container_name: vault
    image: hashicorp/vault:1.13.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"
    ports:
      - "8200:8200"






