apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-istio-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-istio-demo
  template:
    metadata:
      labels:
        app: postgresql-istio-demo
    spec:
      containers:
        - name: app
          image: postgresql-istio-demo:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-istio-demo
spec:
  selector:
    app: postgresql-istio-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080