---
images:
  server: quay.io/infinispan/server:15.0
  initContainer: registry.access.redhat.com/ubi8-micro
deploy:
  # Create a cluster with 3 pods.
  replicas: 3
  # Add a user with full security authorization only until testing is done
  security:
    batch: "user create admin -p changeme -g admin"
  container:
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 2Gi
    storage:
      ephemeral: true
    extraJvmOpts: "-XX:+PrintCommandLineFlags -XX:+UseG1GC -Xmx1536m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=5000 -Dcom.sun.management.jmxremote.rmi.port=5000 -Djava.rmi.server.hostname=127.0.0.1"
  infinispan:
    cacheContainer:
      statistics: true # Global statistics
      jmx:
        enabled: true
        domain: localhost
      distributedCacheConfiguration:
        name: distributed
        mode: SYNC
        statistics: true # Cache statistics
        owners: 2
        segments: 256
        encoding:
          mediaType: "application/x-java-serialized-object"
        expiration:
          # lastUsed + maxIdle < currentTime then Infinispan detects that the entry is expired.
          maxIdle: 300000
        memory:
          maxCount: 100000
          whenFull: REMOVE
      replicatedCacheConfiguration:
        name: replicated
        mode: ASYNC
        statistics: true # Cache statistics
        encoding:
          mediaType: "application/x-java-serialized-object"
        expiration:
          # lastUsed + maxIdle < currentTime then Infinispan detects that the entry is expired.
          maxIdle: 300000
        memory:
          maxCount: 100000
          whenFull: REMOVE
